import { ISector } from "./ISector";
import { IDissimenationLevel, IFrequency, ISecurity } from "./ILib";
import { IDatabase } from "./IDatabase";

export type IForm = {
  id: number;
  db_id: number;
  name: string;
  code: string;
  decree_num?: string;
  confirmed_date: string;
  confirmed_org1: string;
  confirmed_org2: string;
  sector_id: number;
  sector_other: string;
  sub_sector: string;
  coorperate_org: string;
  description: string;
  source_id: [{ id: string }];
  source_other: string;
  collection_method_id: [{ id: string }];
  collection_method_other: string;
  frequency_id: number;
  frequency_other: string;
  collection_started_date: string;
  dissimenation_level_id: number;
  is_form_guide: boolean;
  form_guide_decree_num: string;
  collected_officer: string;
  security_level_id: number;
  owner_department: string;
  owner_email: string;
  owner_phone: string;
  form_generated_date: string;
  form_updated_date: string;
  form_table_count: number;
  estimated_indicators: string;
  keywords: string;
  files: string;
  is_active: boolean;
  version: string;
  sector: ISector;
  frequency: IFrequency;
  dissimenation_level: IDissimenationLevel;
  security_level: ISecurity;
  database: IDatabase;
};
